### PR TITLE
Removes gulp-eslint from production dependencies and updates packages to latest version

### PR DESCRIPTION
**Pull request by pragmaticivan**
OBS: It does not update the following packages due to api incompatibility:
```
eslint-config-liferay   ^1.0.1  →  ^2.0.18
sinon                   ^1.17.2 →  ^5.0.7
webpack                 ^2.5.1  →  ^4.8.1
```

It fixes one of the vulnerabilities.

### CODE REVIEW

**Comment by pragmaticivan** [comment]
BTL saucelabs will not work for PRs anymore since travis dropped jwt value.

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Thank you, pull request merged! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
@pragmaticivan Please note I created an issue and ammended the messages in your commmits to add info to which issue they belong.

**Pull request closed without merging**
